-- MySQL Script generated by MySQL Workbench
-- Tue Jun 11 00:23:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vetcare
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vetcare
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vetcare` DEFAULT CHARACTER SET utf8 ;
USE `vetcare` ;

-- -----------------------------------------------------
-- Table `vetcare`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vetcare`.`user` (
  `iduser` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `birthday` DATETIME NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `postal_code` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `profil_picture` VARCHAR(45) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vetcare`.`race`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vetcare`.`race` (
  `idrace` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idrace`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vetcare`.`veterinarian`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vetcare`.`veterinarian` (
  `idveterinarian` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idveterinarian`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vetcare`.`clinic`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vetcare`.`clinic` (
  `idclinic` INT NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone_number` VARCHAR(45) NOT NULL,
  `veterinarian_idveterinarian` INT NOT NULL,
  PRIMARY KEY (`idclinic`),
  INDEX `fk_clinic_veterinarian1_idx` (`veterinarian_idveterinarian` ASC) VISIBLE,
  CONSTRAINT `fk_clinic_veterinarian1`
    FOREIGN KEY (`veterinarian_idveterinarian`)
    REFERENCES `vetcare`.`veterinarian` (`idveterinarian`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vetcare`.`animal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vetcare`.`animal` (
  `idanimal` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `profil_picture` VARCHAR(45) NULL,
  `birthday` DATETIME NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `race_idrace` INT NOT NULL,
  `clinic_idclinic` INT NOT NULL,
  `user_iduser` INT NOT NULL,
  PRIMARY KEY (`idanimal`),
  INDEX `fk_animal_race_idx` (`race_idrace` ASC) VISIBLE,
  INDEX `fk_animal_clinic1_idx` (`clinic_idclinic` ASC) VISIBLE,
  INDEX `fk_animal_user1_idx` (`user_iduser` ASC) VISIBLE,
  CONSTRAINT `fk_animal_race`
    FOREIGN KEY (`race_idrace`)
    REFERENCES `vetcare`.`race` (`idrace`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_clinic1`
    FOREIGN KEY (`clinic_idclinic`)
    REFERENCES `vetcare`.`clinic` (`idclinic`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_animal_user1`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `vetcare`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
